### PR TITLE
feat: support parallel invocation in powertuning

### PR DESCRIPTION
**Pull request by claydanford**

### CODE REVIEW

**Comment by claydanford** [comment]
@theburningmonk How about now?

**Review by theburningmonk — APPROVED** [review]
yup, all good 👍

**Comment by claydanford** [comment]
@theburningmonk how do I merge it?

**Comment by theburningmonk** [comment]
I'm checking with the Lumigo team to see what's up with the circleci build, I need it to run before I can merge.

**Comment by efimk-lu** [comment]
Hey @claydanford , prettier failed

**Comment by claydanford** [comment]
@theburningmonk @efimk-lu CI passes. I cannot see where to merge it. Would you kindly merge/release?

**Pull request merged**
