### PR TITLE
Optional parallel invocation in power tuning

### LINKED ISSUE #103: how to enable parallel invocation, which input should be passed to the command
Returns only function name because of timeout error, please let me know how to enable parallel invocation

### PR DESCRIPTION
**Pull request by claydanford**
Closes #103

### CODE REVIEW

**Comment by claydanford** [comment]
Hi @theburningmonk, Any chance this can get a review?

Kindly,

CRD

**Review by theburningmonk — APPROVED** [review]
LGTM

**Comment by theburningmonk** [comment]
@claydanford the change looks good to me, but I can't merge this because it doesn't follow conventional commit and our pipeline needs it to work out the next semantic version. Can you resubmit the PR and make sure the commit messages follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format?

**Review by theburningmonk — CHANGES_REQUESTED** [review]
need conventional commit message

**Pull request closed without merging**
